bookmarks/bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('tinymce/', include('tinymce.urls')),
    path('search/', include('search.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'image', views.ImageViewSet)

app_name = 'images'
urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('add/', views.image_add, name='add'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('edit/<int:id>', views.edit, {}, name='edit'),
    path('', include(router.urls)),
]

bookmarks/images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
from django.core.validators import RegexValidator
from tinymce.models import HTMLField

class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField(blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)
    total_view = models.PositiveIntegerField(db_index=True, default=0)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True, max_length=20000)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-created',)

class Comment(models.Model):
    post = models.ForeignKey(Image, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comment_created', on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'on {}'.format(self.post)

    def get_absolute_url(self):
        return self.post.get_absolute_url()

bookmarks/images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from tinymce.widgets import TinyMCE
from django.utils.text import slugify

class ImageCreateForm(forms.ModelForm):
    description = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {'url': forms.HiddenInput, }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(
            slugify(image.title),
            image_url.rsplit('.', 1)[1].lower())
        # Скачиваем изображение по указанному адресу.
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)
        if commit:
            image.save()
        return image

class ImageAddForm(forms.ModelForm):
    description = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    class Meta:
        model = Image
        fields = ('title', 'description', 'image')

class ImageEditForm(forms.ModelForm):
    description = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    class Meta:
        model = Image
        fields = ('title', 'description', 'image')


from .models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

bookmarks/images/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm, ImageAddForm, CommentForm, ImageEditForm
from django.shortcuts import get_object_or_404
from django.http import JsonResponse, HttpResponse, HttpResponseNotFound
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from actions.utils import create_action
from rest_framework import viewsets
from .models import Image, Comment
from common.decorators import ajax_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .serializers import ImageSerializer, UserSerializer

@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'bookmarked image', new_item)
            messages.success(request, 'Image added successfully')
            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)
    return render(request,
                  'images/image/create.html',
                  {'section': 'posts',
                   'form': form})

@login_required
def image_detail(request, id, slug):
    post = get_object_or_404(Image, id=id, slug=slug)
    comments = post.comments.filter(active=True)
    a = post
    a.total_view +=1
    a.save()
    new_comment = None
    comment_form = None
    if request.method == 'POST':
        # Пользователь отправил комментарий.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем в базе данных.
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье.
            new_comment.user = request.user
            new_comment.post_id = id
            # Сохраняем комментарий в базе данных.
            new_comment.save()
            messages.success(request, 'Comment added successfully')
            create_action(request.user, 'Added comment', new_comment)
        else:
            comment_form = CommentForm()
    return render(request, 'images/image/detail.html', {'section': 'posts','image': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form,})

@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'ok'})

@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 25)
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    page_list = page_obj.paginator.page_range
    print(page_obj)
    return render(request, 'images/image/list.html', {'section': 'posts', 'images': page_obj})

@login_required
def image_add(request):
    if request.method == 'POST':
        form = ImageAddForm(data = request.POST, files = request.FILES)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'Added post', new_item)
            messages.success(request, 'Image added successfully')
            return redirect(new_item.get_absolute_url())
    else:
        form = ImageAddForm()

    return render(request, 'images/image/add.html', {'section': 'add post', 'form': form})

@login_required
def edit(request, id):
    data = get_object_or_404(Image, pk=id)
    if request.user.id == data.user_id:
        if request.method == 'POST':
            edit_form = ImageEditForm(instance=data, data=request.POST)
            if edit_form.is_valid():
                edit_form.save()
                messages.success(request, 'Profile updated successfully')
            else:
                messages.error(request, 'Error updating your profile')
        else:
            edit_form = ImageEditForm(instance=data)
        return render(request, 'images/image/edit.html', {'section': 'posts', 'edit_form': edit_form, })
    else:
        return HttpResponseNotFound('<h1>Access denied</h1>')

class UserViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()

class ImageViewSet(viewsets.ModelViewSet):
    serializer_class = ImageSerializer
    queryset = Image.objects.all()

bookmarks/images/templates/images/image/add.html
{% extends "base.html" %}
{% block title %}Added post{% endblock %}
{% block content %}
    <h1>Add a post</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form enctype="multipart/form-data" method="post">
        {{ form.as_p }}
        {{ form.media }}
        {% csrf_token %}
        <input type="submit" value="Added it!">
    </form>
{% endblock %}

bookmarks/images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %}Create post{% endblock %}
{% block content %}
    <h1>Bookmark an image</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Bookmark it!">
    </form>
{% endblock %}

bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}
    <h1>{{ image.title }}</h1>
<div style="background-color: white;">
    {% load thumbnail %}
        {% thumbnail image.image "600" as im %}
        <a href="{{ image.image.url }}">
        <img src="{{ im.url }}" class="image-detail">
        </a>
    {% endthumbnail %}
    {% with users_like=image.users_like.all %}

        <div class="image-info" style="display: inline-block">
                <span class="tooltip">
                    {{ image.total_likes }} like{{ image.total_likes|pluralize }}</span></div>
                <div style="display: inline-block">
                <span class="count" >
                    {{ image.total_view }} view{{ image.total_view|pluralize }}
                </span>
                </div>
                <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                {% if request.user not in image.users_like.all %}
                    Like
                {% else %}
                    Unlike
                {% endif %}
                </a>
                {% if request.user == image.user %}
                    <a href="/images/edit/{{ image.id }}">edit post</a>
                {% endif %}
            </div>
        <div class="post-card"
        {{ image.description|safe }}
             </div>
        </div>
    {% endwith %}
</div>
    <h2  style=" margin-left: 2%; margin-top: 60px">Comments:</h2>
    {% for comment in comments %}
        <div class="comment">
        <p class="info">
        Comment by {{ comment.user }}
        {{ comment.created }}
        </p>
        {{ comment.body }}
        </div>
        {% empty %}
            <p> No commnts yetp</p>
    {% endfor %}

    {% if new_comment %}

    {% else %}
        <form action="." method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment" style="width: 60%"></p>
        </form>
    {% endif %}
{% endblock %}
{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
          // toggle link text
          $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

          // update total likes
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
        }
      }
    );
  });
{% endblock %}

bookmarks/images/templates/images/image/edit.html
{% extends "base.html" %}
{% block title %}Edit your post{% endblock %}
{% block content %}
    <h1>Edit your post</h1>
    <p>You can edit your post using the following form:</p>
    <form action="{% url 'images:edit' id=edit_form.instance.pk %}" method="post" enctype="multipart/form-data">
        {{ edit_form.as_p }}
        {{ edit_form.media }}
        {% csrf_token %}
        <p><input type="submit" value="Save changes"></p>
    </form>
{% endblock %}

bookmarks/images/templates/images/image/list.html
{% extends "base.html" %}
{% block title %}All posts{% endblock %}
{% block content %}
  <h1>All posts</h1>
  <div id="image-list">
    {% include "images/image/post_list.html" %}
    {% include "pagination.html" with page=images %}
  </div>
{% endblock %}

bookmarks/images/templates/images/image/post_list.html
{% for image in images %}
<div class="row">
    <div class="leftcolumn">
        <div class="card">
            <h2><a href="{{ image.get_absolute_url }}">{{image.title}}</a></h2>
            <h5><a href="{{ image.user.get_absolute_url }}">{{image.user.first_name}} {{image.user.last_name}}</a>
                {{image.created|timesince}}</h5>
            <a href="{{ image.get_absolute_url }}">
                <img src="/media/{{ image.image }}">
            </a>
            <p>{{image.description|safe}}</p>
            <a href="{{image.get_absolute_url}}">
                <div class="footer">
                    Watch more...
                </div>
            </a>
        </div></div></div>
{% endfor %}